// Типы действий для авторизации пользователя

module.exports = {

  // Запрос токена от бэк-сервиса
  GET_HEADER_AUTH_TOKEN_REQUEST: 'GET_HEADER_AUTH_TOKEN_REQUEST',
  GET_HEADER_AUTH_TOKEN_SUCCESS: 'GET_HEADER_AUTH_TOKEN_SUCCESS',
  GET_HEADER_AUTH_TOKEN_FAILURE: 'GET_HEADER_AUTH_TOKEN_FAILURE',

  // Запрос списка разделов
  GET_CHAPTERS_LIST_REQUEST: 'GET_CHAPTERS_LIST_REQUEST',
  GET_CHAPTERS_LIST_SUCCESS: 'GET_CHAPTERS_LIST_SUCCESS',
  GET_CHAPTERS_LIST_FAILURE: 'GET_CHAPTERS_LIST_FAILURE',

  // Запрос списка записей в разделе
  GET_ITEMS_LIST_REQUEST: 'GET_ITEMS_LIST_REQUEST',
  GET_ITEMS_LIST_SUCCESS: 'GET_ITEMS_LIST_SUCCESS',
  GET_ITEMS_LIST_FAILURE: 'GET_ITEMS_LIST_FAILURE',

};
